export default [
  {
    activityId: 'k1avj04p',
    activityName: 'تأكيد البيانات',
    status: 'new',
    state: 'Processing',
    userSlug: 'citizen',
    previousStatus: false,
    steps: [
      {
        name: 'تأكيد البيانات',
        fieldsSchema: {
          plateNumber: {
            label: 'رقم اللوحة',
            uuid: 'plateNumber',
            optional: true,
            internal: false,
            showField: false,
            editable: false,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
            defaultValue: 'ج ه ف - 5644',
          },
          postOfficeBarcode: {
            label: 'postOfficeBarcode',
            uuid: 'postOfficeBarcode',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            unique: true,
            index: {
              unique: true,
              sparse: true,
            },
            uniforms: {
              options: [
                {
                  label: 'Option 1',
                  value: 'option-1',
                },
              ],
            },
            defaultValue: [],
            type: 'Array',
          },
          chkResponseCode: {
            label: 'response code',
            uuid: 'chkResponseCode',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
            defaultValue: '200',
          },
          culturedMsg: {
            label: 'Text Field',
            uuid: 'culturedMsg',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
            defaultValue: 'يمكن التجديد ولكن المركبة تحتاج ملصق الكتروني، لذا يجب استلام الرخصة من وحدة المرور، وسوف يتم إرسال شهادة براءة الذمة إلى العنوان المدخل',
          },
          'postOfficeBarcode.$': {
            allowedValues: [
              'option-1',
            ],
            type: 'String',
            optional: true,
          },
        },
        metaFields: [
          {
            path: 'Allowance.vehicleData',
            from: 'serviceHooks',
          },
          {
            path: 'Allowance.warning',
            from: 'serviceHooks',
          },
          {
            path: 'termsAndConditions',
            from: 'serviceHooks',
          },
        ],
      },
      {
        name: 'اختيار مدة التجديد',
        fieldsSchema: {
          renewalDuration: {
            label: 'عدد سنين التجديد',
            uuid: 'renewalDuration',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            uniforms: {},
            schema: {
              RenewYear: {
                label: 'مدة التجديد',
                uuid: 'RenewYear',
                optional: true,
                internal: false,
                showField: false,
                editable: false,
                hidden: false,
                visible: true,
                uniforms: {},
                type: 'String',
              },
              RenewFees: {
                label: 'تكلفة التجديد والتأمين',
                uuid: 'RenewFees',
                optional: true,
                internal: false,
                showField: false,
                editable: false,
                hidden: false,
                visible: true,
                uniforms: {},
                type: 'String',
              },
              TotalFineValue: {
                label: 'إجمالى المخالفات',
                uuid: 'TotalFineValue',
                optional: true,
                internal: false,
                showField: false,
                editable: false,
                hidden: false,
                visible: true,
                uniforms: {},
                type: 'String',
              },
              TotalRenewalFees: {
                label: 'الإجمالى',
                uuid: 'TotalRenewalFees',
                optional: true,
                internal: false,
                showField: false,
                editable: false,
                hidden: false,
                visible: true,
                uniforms: {},
                type: 'String',
              },
            },
            render: {
              type: 'hTable',
              include: [
                'RenewYear',
              ],
              actions: [
                'radio',
              ],
            },
            type: 'Array',
            defaultValue: [
              {
                RenewFees: '3151.7 جنيه',
                RenewYear: '3',
                TotalFineValue: '100 جنيه',
                TotalRenewalFees: '3251.7 جنيه',
              },
              {
                RenewFees: '2168.5 جنيه',
                RenewYear: '2',
                TotalFineValue: '100 جنيه',
                TotalRenewalFees: '2268.5 جنيه',
              },
              {
                RenewFees: '1185.3 جنيه',
                RenewYear: '1',
                TotalFineValue: '100 جنيه',
                TotalRenewalFees: '1285.3 جنيه',
              },
            ],
          },
          Group_contactInfo: {
            label: 'بيانات الاتصال',
            uuid: 'contactInfo',
            optional: true,
            internal: false,
            showField: false,
            editable: false,
            hidden: false,
            visible: true,
            uniforms: {},
            type: 'Object',
          },
          'Group_contactInfo.mobile': {
            label: 'رقم الموبايل',
            uuid: 'mobile',
            optional: true,
            internal: false,
            showField: false,
            editable: false,
            regExp: 'phoneNumber',
            hidden: false,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
            defaultValue: '01000050030',
          },
          'Group_contactInfo.email': {
            label: 'البريد الالكترونى',
            uuid: 'email',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            regExp: 'email',
            hidden: false,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
            defaultValue: 'mq@mcit.com',
          },
        },
        metaFields: [],
      },
    ],
    paymentDetails: {},
  },
  {
    activityId: 'delivery',
    activityName: 'الاستلام',
    status: 'submitDeliveryAddress',
    state: 'Processing',
    userSlug: 'citizen',
    previousStatus: 'new',
    steps: [
      {
        name: 'بيانات الاستلام',
        fieldsSchema: {
          chkResponseCode: {
            label: 'Response code',
            uuid: 'chkResponseCode',
            optional: true,
            internal: false,
            showField: false,
            editable: false,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          deliveryTypeExcluded: {
            uuid: 'deliveryTypeExcluded',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            conditionalField: {
              behavior: 'show',
              operator: 'and',
              conditions: [
                {
                  field: 'chkResponseCode',
                  relation: 'is',
                  value: '200',
                  fieldName: 'chkResponseCode',
                },
              ],
            },
            uniforms: {
              options: [
                {
                  label: 'سأقوم باستلام الرخصة بنفسى من وحدة المرور',
                  value: '2',
                },
              ],
            },
            defaultValue: [],
            type: 'Array',
          },
          DeliveryType: {
            allowedValues: [
              '2',
              '1',
            ],
            uuid: 'DeliveryType',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            conditionalField: {
              behavior: 'show',
              operator: 'and',
              conditions: [
                {
                  field: 'chkResponseCode',
                  relation: 'is',
                  value: '201',
                  fieldName: 'chkResponseCode',
                },
              ],
            },
            uniforms: {
              options: [
                {
                  label: 'سأقوم باستلام الرخصة بنفسى من وحدة المرور ',
                  value: '2',
                },
                {
                  label: 'التوصيل الي عنوانى',
                  value: '1',
                },
              ],
              checkboxes: true,
            },
            type: 'String',
            defaultValue: '2',
          },
          HasClearanceCertificateLicense: {
            label: 'HasClearanceCertificateLicense',
            uuid: 'HasClearanceCertificateLicense',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          ApplicantAddressGovernCode: {
            label: 'المحافظة',
            uuid: 'ApplicantAddressGovernCode',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            conditionalField: {
              behavior: 'show',
              operator: 'or',
              conditions: [
                {
                  field: 'DeliveryType',
                  relation: 'is',
                  value: '1',
                  fieldName: 'DeliveryType',
                },
                {
                  field: 'HasClearanceCertificateLicense',
                  relation: 'is',
                  value: 'false',
                  fieldName: 'HasClearanceCertificateLicense',
                },
              ],
            },
            uniforms: {
              options: [
                {
                  label: 'القاهرة',
                  value: '369',
                },
                {
                  label: 'دمياط',
                  value: '370',
                },
                {
                  label: 'الدقهلية',
                  value: '371',
                },
                {
                  label: 'الشرقية',
                  value: '372',
                },
                {
                  label: 'القليوبية',
                  value: '373',
                },
                {
                  label: 'كفر الشيخ',
                  value: '374',
                },
                {
                  label: 'الغربية',
                  value: '375',
                },
                {
                  label: 'المنوفية',
                  value: '376',
                },
                {
                  label: 'البحيرة',
                  value: '377',
                },
                {
                  label: 'الإسماعيلية',
                  value: '378',
                },
                {
                  label: 'الإسكندرية',
                  value: '379',
                },
                {
                  label: 'الجيزة',
                  value: '380',
                },
                {
                  label: 'بني سويف',
                  value: '381',
                },
                {
                  label: 'الفيوم',
                  value: '382',
                },
                {
                  label: 'المنيا',
                  value: '383',
                },
                {
                  label: 'أسيوط',
                  value: '384',
                },
                {
                  label: 'سوهاج',
                  value: '385',
                },
                {
                  label: 'قنا',
                  value: '386',
                },
                {
                  label: 'أسوان',
                  value: '387',
                },
                {
                  label: 'الأقصر',
                  value: '388',
                },
                {
                  label: 'بورسعيد',
                  value: '389',
                },
                {
                  label: 'البحر الأحمر',
                  value: '390',
                },
                {
                  label: 'الوادي الجديد',
                  value: '391',
                },
                {
                  label: 'مطروح',
                  value: '392',
                },
                {
                  label: 'شمال سيناء',
                  value: '393',
                },
                {
                  label: 'جنوب سيناء',
                  value: '394',
                },
                {
                  label: 'السويس',
                  value: '395',
                },
                {
                  label: 'حلوان',
                  value: '396',
                },
                {
                  label: '6 اكتوبر',
                  value: '397',
                },
                {
                  label: 'خارج الجمهورية',
                  value: '398',
                },
              ],
            },
            type: 'String',
            allowedValues: [
              '369',
              '370',
              '371',
              '372',
              '373',
              '374',
              '375',
              '376',
              '377',
              '378',
              '379',
              '380',
              '381',
              '382',
              '383',
              '384',
              '385',
              '386',
              '387',
              '388',
              '389',
              '390',
              '391',
              '392',
              '393',
              '394',
              '395',
              '396',
              '397',
              '398',
            ],
            defaultValue: '369',
          },
          ApplicantBuildingNo: {
            label: 'رقم المبنى',
            uuid: 'ApplicantBuildingNo',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            conditionalField: {
              behavior: 'show',
              operator: 'or',
              conditions: [
                {
                  field: 'DeliveryType',
                  relation: 'is',
                  value: '1',
                  fieldName: 'DeliveryType',
                },
                {
                  field: 'HasClearanceCertificateLicense',
                  relation: 'is',
                  value: 'false',
                  fieldName: 'HasClearanceCertificateLicense',
                },
              ],
            },
            max: '5',
            min: '1',
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          ApplicantFlatNo: {
            label: 'رقم الشقة',
            uuid: 'ApplicantFlatNo',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            conditionalField: {
              behavior: 'show',
              operator: 'or',
              conditions: [
                {
                  field: 'DeliveryType',
                  relation: 'is',
                  value: '1',
                  fieldName: 'DeliveryType',
                },
                {
                  field: 'HasClearanceCertificateLicense',
                  relation: 'is',
                  value: 'false',
                  fieldName: 'HasClearanceCertificateLicense',
                },
              ],
            },
            max: '5',
            min: '1',
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          ApplicantFloorNo: {
            label: 'رقم الدور',
            uuid: 'ApplicantFloorNo',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            conditionalField: {
              behavior: 'show',
              operator: 'or',
              conditions: [
                {
                  field: 'DeliveryType',
                  relation: 'is',
                  value: '1',
                  fieldName: 'DeliveryType',
                },
                {
                  field: 'HasClearanceCertificateLicense',
                  relation: 'is',
                  value: 'false',
                  fieldName: 'HasClearanceCertificateLicense',
                },
              ],
            },
            max: '5',
            min: '1',
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          ApplicantAddress: {
            label: 'عنوان الاستلام بالتفصيل',
            uuid: 'ApplicantAddress',
            optional: false,
            internal: false,
            showField: false,
            editable: true,
            hidden: false,
            visible: true,
            conditionalField: {
              behavior: 'show',
              operator: 'or',
              conditions: [
                {
                  field: 'DeliveryType',
                  relation: 'is',
                  value: '1',
                  fieldName: 'DeliveryType',
                },
                {
                  field: 'HasClearanceCertificateLicense',
                  relation: 'is',
                  value: 'false',
                  fieldName: 'HasClearanceCertificateLicense',
                },
              ],
            },
            max: '100',
            min: '1',
            uniforms: {
              type: 'textarea',
            },
            type: 'String',
          },
          price_issueRenewReqTotalPrice: {
            label: 'رسوم التجديد والتأمين',
            uuid: 'price_issueRenewReqTotalPrice',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          price_fines: {
            label: 'المخالفات والرسوم',
            uuid: 'price_fines',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          price_PICServiceValue: {
            label: 'رسوم شهادة براءة الذمة',
            uuid: 'price_PICServiceValue',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          price_clrCertDelivery: {
            label: 'رسوم شحن شهادة براءة الذمة',
            uuid: 'price_clrCertDelivery',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          totalPrice: {
            label: 'المجموع',
            uuid: 'totalPrice',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          price_drvLicDelivery: {
            label: 'رسوم شحن الرخصة',
            uuid: 'price_drvLicDelivery',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          drvLicBarcode: {
            label: 'drvLicBarcode',
            uuid: 'drvLicBarcode',
            optional: true,
            internal: false,
            showField: false,
            editable: true,
            hidden: true,
            visible: true,
            uniforms: {
              type: 'text',
            },
            type: 'String',
          },
          clrCertBarcode: {
            label: 'clrCertBarcode',
            uuid: 'clrCertBarcode',
            optional: true,
            internal: false,
            showField: false,
            editable: false,
            hidden: true,
            visible: true,
            uniforms: {},
            type: 'Array',
          },
          'deliveryTypeExcluded.$': {
            allowedValues: [
              '2',
            ],
            type: 'String',
            optional: true,
          },
          'clrCertBarcode.$': {
            uniforms: {
              type: 'text',
            },
            type: 'String',
            label: 'clrCertBarcode',
          },
        },
        metaFields: [
          {
            path: 'violationsDetails',
            from: 'requestHooks',
          },
        ],
      },
    ],
    paymentDetails: {},
  },
  {
    activityId: 'issueNewRequest',
    activityName: 'الدفع',
    status: 'paymentCompleted',
    state: 'Processing',
    userSlug: 'citizen',
    previousStatus: 'submitDeliveryAddress',
    steps: [
      {
        name: 'الدفع',
        fieldsSchema: {
          requestTotalPrice: {
            label: 'totalPrice',
            uuid: 'requestTotalPrice',
            optional: true,
            internal: false,
            showField: false,
            editable: false,
            hidden: false,
            visible: true,
            uniforms: {
              type: 'price',
            },
            type: 'price',
            item: {
              itemName: 'totalPrice',
              max_quantity: '45678907890',
              activity: 'delivery',
              activityField: 'totalPrice',
              amountInsertion: 'employee',
            },
          },
        },
        metaFields: [],
      },
    ],
    paymentDetails: {
      paymentType: 'online',
      currency: 'EGP',
      paymentGateway: 'e-finance',
    },
  },
  {
    activityId: 'k1jp8uuv',
    activityName: 'التأكيد',
    status: 'finished',
    state: 'Approved',
    userSlug: 'citizen',
    previousStatus: 'paymentCompleted',
    steps: [
      {
        name: 'التأكيد',
        metaFields: [
          {
            path: 'confirmation',
            from: 'requestHooks',
          },
        ],
      },
    ],
    paymentDetails: {},
  },
  {
    activityId: 'k1mdlxfd',
    activityName: 'طلب غير ناجح',
    status: 'rejected',
    state: 'Rejected',
    userSlug: 'citizen',
    previousStatus: 'new',
    steps: [
      {
        name: 'طلب غير ناجح',
        metaFields: [
          {
            path: 'n',
            from: 'requestHooks',
          },
        ],
      },
    ],
    paymentDetails: {},
  },
  {
    activityId: 'k1l5wmve',
    activityName: 'خطأ فى الدفع',
    status: 'failedPayment',
    state: 'Rejected',
    userSlug: 'citizen',
    previousStatus: 'submitDeliveryAddress',
    steps: [
      {
        name: 'خطأ فى الدفع',
        metaFields: [
          {
            message: 'عفوا حدث خطأ أثناء عمليه الدفع',
            icon: 'error',
          },
        ],
      },
    ],
    paymentDetails: {},
  },
  {
    activityName: 'تحت التسليم',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: 'finished',
    steps: [],
    paymentDetails: {},
    activityId: 'pendingDeliveryId',
    status: 'pendingDelivery',
    rootActivity: true,
    branches: [
      {
        branchId: 'nyaba',
        enabled: true,
      },
      {
        branchId: 'mror',
        enabled: true,
      },
    ],
  },
  //   {
  //     activityId: 'تم التنفيذ ولم يتم الطباعة',
  //     activityName: 'تم التنفيذ ولم يتم الطباعة',
  //     status: '15',
  //     state: 'Processing',
  //     userSlug: 'GA',
  //     previousStatus: 'pendingDelivery',
  //     steps: [],
  //     rootActivityId: 'pendingDeliveryId',
  //     branchActivity: true,
  //     branchId: 'nyaba',
  //     paymentDetails: {},
  //   },
  {
    activityId: 'تم طباعة المستند',
    activityName: 'تم طباعة المستند',
    status: '215',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: 'pendingDelivery',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    paymentDetails: {},
  },
  //   {
  //     activityId: 'تم الغاء الطلب',
  //     activityName: 'تم الغاء الطلب',
  //     status: '230',
  //     state: 'Rejected',
  //     userSlug: 'GA',
  //     previousStatus: 'finished',
  //     steps: [],
  //     rootActivityId: 'pendingDeliveryId',
  //     branchActivity: true,
  //     branchId: 'nyaba',
  //     optional: true,
  //     paymentDetails: {},
  //   },
  {
    activityId: 'الشحنة جاهزة للتسليم للبريد',
    activityName: 'الشحنة جاهزة للتسليم للبريد',
    status: '321',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: '215',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    paymentDetails: {},
  },
  {
    activityId: 'تم تسليم الشحنة الى البريد',
    activityName: 'تم تسليم الشحنة الى البريد',
    status: '318',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: '321',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    paymentDetails: {},
  },
  {
    activityId: 'تم تأكيد استلام الشحنة من قبل البريد',
    activityName: 'تم تأكيد استلام الشحنة من قبل البريد',
    status: '135',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '318',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    paymentDetails: {},
  },
  {
    activityId: 'جاري تسليم الشحنة',
    activityName: 'جاري تسليم الشحنة',
    status: '14',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '135',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    paymentDetails: {},
  },
  {
    activityId: 'لم يتم العثور على المرسل اليه وسوف يتم اعادة المحاولة في اليوم التالي',
    activityName: 'لم يتم العثور على المرسل اليه وسوف يتم اعادة المحاولة في اليوم التالي',
    status: '54',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '14',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    optional: true,
    paymentDetails: {},
  },
  {
    activityId: 'لم يتم العثور على المرسل اليه ويجب استلام الشحنة من مكتب بريد',
    activityName: 'لم يتم العثور على المرسل اليه ويجب استلام الشحنة من مكتب البريد ',
    status: '500',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '54',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    optional: true,
    paymentDetails: {},
  },
  {
    activityId: 'تم تسليم الشحنة للمرسل اليه',
    activityName: 'تم تسليم الشحنة للمرسل اليه',
    status: '53',
    state: 'Approved',
    userSlug: 'courrier',
    previousStatus: '500',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    paymentDetails: {},
  },
  {
    activityId: 'لم يتم العثور على المرسل اليه وسوف يتم ارجاع الشحنة للمرسل',
    activityName: 'لم يتم العثور على المرسل اليه وسوف يتم ارجاع الشحنة للمرسل',
    status: '112',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '500',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    optional: true,
    paymentDetails: {},
  },
  {
    activityId: 'تم تسليم المستندات المطلوبة للجهة',
    activityName: 'تم تسليم المستندات المطلوبة للجهة',
    status: '340',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '53',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    paymentDetails: {},
  },
  {
    activityId: 'تم استلام الشحنة المرجعة من البريد',
    activityName: 'تم استلام الشحنة المرجعة من البريد',
    status: '342',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: '340',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'nyaba',
    optional: true,
    paymentDetails: {},
  },
  //   {
  //     activityId: 'تم التنفيذ ولم يتم الطباعة',
  //     activityName: 'تم التنفيذ ولم يتم الطباعة',
  //     status: '15',
  //     state: 'Processing',
  //     userSlug: 'GA',
  //     previousStatus: 'finished',
  //     steps: [],
  //     rootActivityId: 'pendingDeliveryId',
  //     branchActivity: true,
  //     branchId: 'mror',
  //     paymentDetails: {},
  //   },
  {
    activityId: 'تم طباعة المستند',
    activityName: 'تم طباعة المستند',
    status: '215',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: 'pendingDelivery',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    paymentDetails: {},
  },
  //   {
  //     activityId: 'تم الغاء الطلب',
  //     activityName: 'تم الغاء الطلب',
  //     status: '230',
  //     state: 'Rejected',
  //     userSlug: 'GA',
  //     previousStatus: 'finished',
  //     steps: [],
  //     rootActivityId: 'pendingDeliveryId',
  //     branchActivity: true,
  //     branchId: 'mror',
  //     optional: true,
  //     paymentDetails: {},
  //   },
  {
    activityId: 'الشحنة جاهزة للتسليم للبريد',
    activityName: 'الشحنة جاهزة للتسليم للبريد',
    status: '321',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: '215',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    paymentDetails: {},
  },
  {
    activityId: 'تم تسليم الشحنة الى البريد',
    activityName: 'تم تسليم الشحنة الى البريد',
    status: '318',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: '321',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    paymentDetails: {},
  },
  {
    activityId: 'تم تأكيد استلام الشحنة من قبل البريد',
    activityName: 'تم تأكيد استلام الشحنة من قبل البريد',
    status: '135',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '318',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    paymentDetails: {},
  },
  {
    activityId: 'جاري تسليم الشحنة',
    activityName: 'جاري تسليم الشحنة',
    status: '14',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '135',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    paymentDetails: {},
  },
  {
    activityId: 'لم يتم العثور على المرسل اليه وسوف يتم اعادة المحاولة في اليوم التالي',
    activityName: 'لم يتم العثور على المرسل اليه وسوف يتم اعادة المحاولة في اليوم التالي',
    status: '54',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '14',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    optional: true,
    paymentDetails: {},
  },
  {
    activityId: 'لم يتم العثور على المرسل اليه ويجب استلام الشحنة من مكتب بريد',
    activityName: 'لم يتم العثور على المرسل اليه ويجب استلام الشحنة من مكتب البريد ',
    status: '500',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '54',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    optional: true,
    paymentDetails: {},
  },
  {
    activityId: 'تم تسليم الشحنة للمرسل اليه',
    activityName: 'تم تسليم الشحنة للمرسل اليه',
    status: '53',
    previousStatusArray: ['500', '54', '14'],
    state: 'Approved',
    userSlug: 'courrier',
    previousStatus: '500',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    paymentDetails: {},
  },
  {
    activityId: 'لم يتم العثور على المرسل اليه وسوف يتم ارجاع الشحنة للمرسل',
    activityName: 'لم يتم العثور على المرسل اليه وسوف يتم ارجاع الشحنة للمرسل',
    status: '112',
    state: 'Processing',
    userSlug: 'courrier',
    previousStatus: '500',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    optional: true,
    paymentDetails: {},
  },
  {
    activityId: 'تم استلام الشحنة المرجعة من البريد',
    activityName: 'تم استلام الشحنة المرجعة من البريد',
    status: '342',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: '112',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    branchActivity: true,
    branchId: 'mror',
    optional: true,
    paymentDetails: {},
  },
  {
    status: 'requestDone',
    state: 'Processing',
    userSlug: 'GA',
    previousStatus: 'pendingDelivery',
    steps: [],
    rootActivityId: 'pendingDeliveryId',
    closingActivity: true,
    isPrivateComment: false,
    activityName: 'تم انهاء الطلب',
    activityDescription: 'تم انهاء الطلب',
    activityId: 'تم انهاء الطلب',
    paymentDetails: {},
  },
];

export const history = [
  {
    user: {
      id: '5f3695c81a8fcd311eca178a',
      username: '28705290101637',
      principalType: 'citizen',
    },
    time: '2020-09-16T10:36:32.625Z',
    action: 'create',
    newStatus: 'new',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: false,
    data: {
      plateNumber: 'ل أ ص - 957',
      postOfficeBarcode: [
        'EIPB0000098EG',
        'EITB0000098EG',
      ],
      chkResponseCode: '201',
      renewalDuration: [
        {
          RenewYear: '1',
        },
      ],
      Group_contactInfo: {
        mobile: '01000123335',
        email: 'monzeirmoneir@gmail.com',
      },
    },
    isPrivateComment: false,
    activityName: 'تأكيد البيانات',
    activityDescription: '',
    activityId: 'k1avj04p',
    userAgent: {
      os: {
        family: 'Windows',
        major: '10',
        minor: '0',
        patch: '0',
      },
      device: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      browser: {
        family: 'Chrome',
        major: '85',
        minor: '0',
        patch: '4183',
      },
      ip: '197.62.81.173',
    },
  },
  {
    user: {
      id: '5f3695c81a8fcd311eca178a',
      username: '28705290101637',
      principalType: 'citizen',
    },
    time: '2020-09-16T10:38:22.713Z',
    action: 'patchAttributes',
    status: 'new',
    state: 'Processing',
    newStatus: 'submitDeliveryAddress',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: true,
    data: {
      chkResponseCode: '201',
      deliveryTypeExcluded: [],
      DeliveryType: '1',
      HasClearanceCertificateLicense: 'false',
      ApplicantAddressGovernCode: '369',
      ApplicantBuildingNo: '168',
      ApplicantFlatNo: '3',
      ApplicantFloorNo: '0',
      ApplicantAddress: '168 شارع جسر السويس بجوار محطة مترو قباء - النزهة الجديدة - القاهرة',
      price_issueRenewReqTotalPrice: '1299.70',
      price_fines: '15.00',
      price_PICServiceValue: '20',
      price_clrCertDelivery: '15',
      totalPrice: '1364.70',
      price_drvLicDelivery: '15',
      drvLicBarcode: 'EITB0000098EG',
      clrCertBarcode: 'EIPB0000098EG',
    },
    isPrivateComment: false,
    activityName: 'الاستلام',
    activityDescription: '',
    activityId: 'delivery',
    userAgent: {
      os: {
        family: 'Windows',
        major: '10',
        minor: '0',
        patch: '0',
      },
      device: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      browser: {
        family: 'Chrome',
        major: '85',
        minor: '0',
        patch: '4183',
      },
      ip: '197.62.81.173',
    },
  },
  {
    user: {
      id: '5f3695c81a8fcd311eca178a',
      username: '28705290101637',
      principalType: 'citizen',
    },
    time: '2020-09-16T10:38:49.337Z',
    action: 'startPayment',
    status: 'submitDeliveryAddress',
    state: 'Processing',
    newStatus: 'submitDeliveryAddress',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: false,
    data: {
      requestTotalPrice: '1',
    },
    isPrivateComment: false,
    activityName: 'الاستلام',
    activityDescription: '',
    activityId: 'delivery',
    userAgent: {
      os: {
        family: 'Windows',
        major: '10',
        minor: '0',
        patch: '0',
      },
      device: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      browser: {
        family: 'Chrome',
        major: '85',
        minor: '0',
        patch: '4183',
      },
      ip: '197.62.81.173',
    },
  },
  {
    user: {
      id: '5f3695c81a8fcd311eca178a',
      username: '28705290101637',
      principalType: 'citizen',
    },
    time: '2020-09-16T10:39:33.535Z',
    action: 'startPayment',
    status: 'submitDeliveryAddress',
    state: 'Processing',
    newStatus: 'submitDeliveryAddress',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: false,
    data: {
      requestTotalPrice: '1',
    },
    isPrivateComment: false,
    activityName: 'الاستلام',
    activityDescription: '',
    activityId: 'delivery',
    paymentRequestNumber: 'b969d3abaacd4f05',
    secret: 'hbtY7zTbTkjFS+QPcj30gWr3Rh0LKN34axy+Hgcz1Qrx6mLJziEufikcf5XYPKsK',
    userAgent: {
      os: {
        family: 'Windows',
        major: '10',
        minor: '0',
        patch: '0',
      },
      device: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      browser: {
        family: 'Chrome',
        major: '85',
        minor: '0',
        patch: '4183',
      },
      ip: '197.62.81.173',
    },
  },
  {
    user: {
      id: '5f3695c81a8fcd311eca178a',
      username: '28705290101637',
      principalType: 'citizen',
    },
    time: '2020-09-16T10:40:24.335Z',
    action: 'finishPayment',
    status: 'submitDeliveryAddress',
    state: 'Processing',
    newStatus: 'paymentCompleted',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: false,
    data: {

    },
    isPrivateComment: false,
    activityName: 'الدفع',
    activityDescription: '',
    activityId: 'issueNewRequest',
    userAgent: {
      os: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      device: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      browser: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      ip: '196.46.22.20',
    },
    totalAmount: '1382.99',
    checkoutDate: '2020-09-16T12:39:33.993',
    paymentMeta: {
      'xmlns:xsd': 'http://www.w3.org/2001/XMLSchema',
      'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
      Sender: {
        Id: '12',
        Name: 'efinance',
        RandomValue: '5MmFx6zMktTQY4DkFz0mZ9t1KgLPlUysilX8uclgi2SRcGM3/6hzAetGf1kzOa3p',
        Password: '3JkpO8sYzibgVe9V9tAp4g==',
      },
      SenderRequestNumber: 'afefc3150c914e47',
      PaymentRequestNumber: '20091600000413',
      PaymentRequestTotalAmount: '1382.99',
      CollectionFeesAmount: '18.29',
      CustomerAuthorizationAmount: '1364.7',
      AuthorizationCode: '650676',
      AuthorizingMechanism: 'Card',
      AuthoriztionDateTime: '2020-09-16T12:39:33.993',
      ReconciliationDate: '2020-09-16T12:39:33.993',
      IsConfirmed: 'true',
      RequestSourceId: '0',
    },
    paid: true,
    currency: 'EGP',
  },
  {
    user: {
      id: '5f3695c81a8fcd311eca178a',
      username: '28705290101637',
      principalType: 'citizen',
    },
    time: '2020-09-16T10:40:43.250Z',
    action: 'confirmPayment',
    status: 'paymentCompleted',
    state: 'Processing',
    newStatus: 'paymentCompleted',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: false,
    data: {

    },
    isPrivateComment: false,
    activityName: 'الدفع',
    activityDescription: '',
    activityId: 'issueNewRequest',
    userAgent: {
      os: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      device: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      browser: {
        family: 'Other',
        major: '0',
        minor: '0',
        patch: '0',
      },
      ip: '196.46.22.20',
    },
    totalAmount: '1382.99',
    checkoutDate: '2020-09-16T12:39:33.993',
    paymentMeta: {
      'xmlns:xsd': 'http://www.w3.org/2001/XMLSchema',
      'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
      Sender: {
        Id: '12',
        Name: 'efinance',
        RandomValue: '5MmFx6zMktTQY4DkFz0mZ9t1KgLPlUysilX8uclgi2SRcGM3/6hzAetGf1kzOa3p',
        Password: '3JkpO8sYzibgVe9V9tAp4g==',
      },
      SenderRequestNumber: 'afefc3150c914e47',
      PaymentRequestNumber: '20091600000413',
      PaymentRequestTotalAmount: '1382.99',
      CollectionFeesAmount: '18.29',
      CustomerAuthorizationAmount: '1364.7',
      AuthorizationCode: '650676',
      AuthorizingMechanism: 'Card',
      AuthoriztionDateTime: '2020-09-16T12:39:33.993',
      ReconciliationDate: '2020-09-16T12:39:33.993',
      IsConfirmed: 'true',
      RequestSourceId: '0',
    },
  },
  {
    activityId: 'k1jp8uuv',
    activityName: 'التأكيد',
    newStatus: 'finished',
    state: 'Approved',
    userSlug: 'citizen',
    previousStatus: 'paymentCompleted',
    steps: [
      {
        name: 'التأكيد',
        metaFields: [
          {
            path: 'confirmation',
            from: 'requestHooks',
          },
        ],
      },
    ],
    paymentDetails: {},
  },
  {
    user: {
      id: '5d10b1af698d4e909ee08935',
      firstName: 'Egypt',
      lastName: 'Smartcards',
      username: 'egyptsmartcards',
      principalType: 'GA',
    },
    activityId: 'pendingDeliveryId',
    rootActivity: true,
    newStatus: 'pendingDelivery',
    status: 'paymentCompleted',
    time: '2020-09-16T10:41:16Z',
    action: 'changeRequestStatus',
    state: 'Processing',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: false,
    data: {

    },
    isPrivateComment: false,
    activityName: 'تحت التسليم ',
    activityDescription: '',
    branchesHistory: {
      mror: [{
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-09-16T10:41:16Z',
        action: 'changeRequestStatus',
        status: 'paymentCompleted',
        state: 'Processing',
        newStatus: '15',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم التنفيذ ولم يتم الطباعة',
        activityDescription: '',
        activityId: 'تم التنفيذ ولم يتم الطباعة',
      }, {
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-09-17T06:58:07.843Z',
        action: 'changeRequestStatus',
        status: '15',
        state: 'Processing',
        newStatus: '215',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم طباعة المستند',
        activityDescription: '',
        activityId: 'تم طباعة المستند',
      }, {
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-09-17T06:59:05.151Z',
        action: 'changeRequestStatus',
        status: '215',
        state: 'Processing',
        newStatus: '321',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'الشحنة جاهزة للتسليم للبريد',
        activityDescription: 'الشحنة جاهزة للتسليم للبريد',
        activityId: 'الشحنة جاهزة للتسليم للبريد',
      }, {
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-09-17T07:35:17.336Z',
        action: 'changeRequestStatus',
        status: '321',
        state: 'Processing',
        newStatus: '318',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم تسليم الشحنة الى البريد',
        activityDescription: 'تم تسليم الشحنة الى البريد',
        activityId: 'تم تسليم الشحنة الى البريد',
        message: ' نوع الشحنة: رخصة مركبة ',
      },

      {
        user: {
          id: '5ea5530b590e9a702fde00d8',
          firstName: 'postoffice',
          lastName: 'postoffice',
          username: 'postoffice',
          principalType: 'courrier',
        },
        time: '2020-10-14T14:50:16.638Z',
        action: 'changeRequestStatus',
        status: '318',
        state: 'Processing',
        newStatus: '135',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم تأكيد استلام الشحنة من قبل البريد',
        activityDescription: 'تم تأكيد استلام الشحنة من قبل البريد',
        activityId: 'تم تأكيد استلام الشحنة من قبل البريد',
        userAgent: {
          os: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          device: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          browser: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          ip: '10.107.148.26',
        },
        message: ' نوع الشحنة: رخصة مركبة ',
      },
      {
        user: {
          id: '5ea5530b590e9a702fde00d8',
          firstName: 'postoffice',
          lastName: 'postoffice',
          username: 'postoffice',
          principalType: 'courrier',
        },
        time: '2020-10-15T06:30:24.713Z',
        action: 'changeRequestStatus',
        status: '135',
        state: 'Processing',
        newStatus: '14',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'جاري تسليم الشحنة',
        activityDescription: 'جاري تسليم الشحنة',
        activityId: 'جاري تسليم الشحنة',
        userAgent: {
          os: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          device: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          browser: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          ip: '10.107.148.26',
        },
        message: ' نوع الشحنة: رخصة مركبة ',
      },
      {
        user: {
          id: '5ea5530b590e9a702fde00d8',
          firstName: 'postoffice',
          lastName: 'postoffice',
          username: 'postoffice',
          principalType: 'courrier',
        },
        time: '2020-10-21T07:40:30.297Z',
        action: 'changeRequestStatus',
        status: '14',
        state: 'Processing',
        newStatus: '53',
        newState: 'Approved',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم تسليم الشحنة للمرسل اليه',
        activityDescription: 'تم تسليم الشحنة للمرسل اليه',
        activityId: 'تم تسليم الشحنة للمرسل اليه',
        userAgent: {
          os: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          device: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          browser: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          ip: '10.107.148.26',
        },
        message: ' نوع الشحنة: رخصة مركبة ',
      },

      ],
      nyaba: [{
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-10-07T14:44:14.023Z',
        action: 'changeRequestStatus',
        status: '321',
        state: 'Processing',
        newStatus: '15',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم التنفيذ ولم يتم الطباعة',
        activityDescription: '',
        activityId: 'تم التنفيذ ولم يتم الطباعة',
      }, {
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-10-13T17:16:34.716Z',
        action: 'changeRequestStatus',
        status: '15',
        state: 'Processing',
        newStatus: '215',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم طباعة المستند',
        activityDescription: '',
        activityId: 'تم طباعة المستند',
      },
      {
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-10-14T14:03:41.269Z',
        action: 'changeRequestStatus',
        status: '215',
        state: 'Processing',
        newStatus: '215',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم طباعة المستند',
        activityDescription: '',
        activityId: 'تم طباعة المستند',
        message: ' نوع الشحنة: شهادة براءة ذمة ',
      }, {
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-10-14T14:04:41.245Z',
        action: 'changeRequestStatus',
        status: '215',
        state: 'Processing',
        newStatus: '321',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'الشحنة جاهزة للتسليم للبريد',
        activityDescription: 'الشحنة جاهزة للتسليم للبريد',
        activityId: 'الشحنة جاهزة للتسليم للبريد',
        message: ' نوع الشحنة: شهادة براءة ذمة ',
      }, {
        user: {
          id: '5d10b1af698d4e909ee08935',
          firstName: 'Egypt',
          lastName: 'Smartcards',
          username: 'egyptsmartcards',
          principalType: 'GA',
        },
        time: '2020-10-14T14:04:41.465Z',
        action: 'changeRequestStatus',
        status: '321',
        state: 'Processing',
        newStatus: '318',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم تسليم الشحنة الى البريد',
        activityDescription: 'تم تسليم الشحنة الى البريد',
        activityId: 'تم تسليم الشحنة الى البريد',
        message: ' نوع الشحنة: شهادة براءة ذمة ',
      },
      {
        user: {
          id: '5ea5530b590e9a702fde00d8',
          firstName: 'postoffice',
          lastName: 'postoffice',
          username: 'postoffice',
          principalType: 'courrier',
        },
        time: '2020-10-14T14:50:16.638Z',
        action: 'changeRequestStatus',
        status: '318',
        state: 'Processing',
        newStatus: '135',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم تأكيد استلام الشحنة من قبل البريد',
        activityDescription: 'تم تأكيد استلام الشحنة من قبل البريد',
        activityId: 'تم تأكيد استلام الشحنة من قبل البريد',
        userAgent: {
          os: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          device: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          browser: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          ip: '10.107.148.26',
        },
        message: ' نوع الشحنة: شهادة براءة ذمة ',
      },
      {
        user: {
          id: '5ea5530b590e9a702fde00d8',
          firstName: 'postoffice',
          lastName: 'postoffice',
          username: 'postoffice',
          principalType: 'courrier',
        },
        time: '2020-10-15T06:30:24.713Z',
        action: 'changeRequestStatus',
        status: '135',
        state: 'Processing',
        newStatus: '14',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'جاري تسليم الشحنة',
        activityDescription: 'جاري تسليم الشحنة',
        activityId: 'جاري تسليم الشحنة',
        userAgent: {
          os: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          device: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          browser: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          ip: '10.107.148.26',
        },
        message: ' نوع الشحنة: شهادة براءة ذمة ',
      },
      {
        user: {
          id: '5ea5530b590e9a702fde00d8',
          firstName: 'postoffice',
          lastName: 'postoffice',
          username: 'postoffice',
          principalType: 'courrier',
        },
        time: '2020-10-21T07:40:30.297Z',
        action: 'changeRequestStatus',
        status: '14',
        state: 'Processing',
        newStatus: '53',
        newState: 'Proccessing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم تسليم الشحنة للمرسل اليه',
        activityDescription: 'تم تسليم الشحنة للمرسل اليه',
        activityId: 'تم تسليم الشحنة للمرسل اليه',
        userAgent: {
          os: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          device: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          browser: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          ip: '10.107.148.26',
        },
        message: ' نوع الشحنة: شهادة براءة ذمة ',
      },
      {
        user: {
          id: '5ea5530b590e9a702fde00d8',
          firstName: 'postoffice',
          lastName: 'postoffice',
          username: 'postoffice',
          principalType: 'courrier',
        },
        time: '2020-10-21T07:41:23.875Z',
        action: 'changeRequestStatus',
        status: '53',
        state: 'Processing',
        newStatus: '340',
        newState: 'Processing',
        internal: false,
        externalStatus: false,
        isEdit: false,
        data: {

        },
        isPrivateComment: false,
        branchActivity: true,
        activityName: 'تم تسليم المستندات المطلوبة للجهة',
        activityDescription: 'تم تسليم المستندات المطلوبة للجهة',
        activityId: 'تم تسليم المستندات المطلوبة للجهة',
        userAgent: {
          os: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          device: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          browser: {
            family: 'Other',
            major: '0',
            minor: '0',
            patch: '0',
          },
          ip: '10.107.148.26',
        },
        message: ' نوع الشحنة: شهادة براءة ذمة ',
      },
      {
        activityId: 'لم يتم العثور على المرسل اليه ويجب استلام الشحنة من مكتب بريد',
        activityName: 'لم يتم العثور على المرسل اليه ويجب استلام الشحنة من مكتب البريد ',
        newStatus: '500',
        state: 'Processing',
        userSlug: 'courrier',
        previousStatus: '54',
        steps: [],
        rootActivityId: 'pendingDeliveryId',
        branchActivity: true,
        branchId: 'nyaba',
        optional: true,
        paymentDetails: {},
      },
      {
        newStatus: '54',
      },
      ],
    },
  },
  {
    user: {
      id: '5ea5530b590e9a702fde00d8',
      firstName: 'postoffice',
      lastName: 'postoffice',
      username: 'postoffice',
      principalType: 'courrier',
    },
    time: '2020-10-21T07:41:23.875Z',
    action: 'changeRequestStatus',
    status: 'pendingDelivery',
    state: 'Approved',
    newStatus: 'requestDone',
    newState: 'Processing',
    internal: false,
    externalStatus: false,
    isEdit: false,
    data: {

    },
    rootActivityId: 'pendingDeliveryId',
    closingActivity: true,
    isPrivateComment: false,
    activityName: 'تم انهاء الطلب',
    activityDescription: 'تم انهاء الطلب',
    activityId: 'تم انهاء الطلب',
  },

];
